version: '3'

services: 
  database:
    image: postgres
    ports: 
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_DB: my_postgres
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: 5432
    restart: always

volumes: 
  postgres_data: